review
pawwwline/cr-task-tracker pull request #1
Opened 2024-09-12 14:26 UTC by pawwwline

2024-09-12 15:33 UTC, lazyfatcot requested changes
Ну а в целом умница)

2024-09-12 15:33 UTC, lazyfatcot commented on storage/files/files.go
Все четко. Реализация интерфейса хранилища. Смотри комментарий про SOLID

2024-09-12 15:33 UTC, lazyfatcot commented on app/service.go
> +		Id:          id + 1,
Смотреть коммент выше

2024-09-12 15:33 UTC, lazyfatcot commented on app/service.go
> +			fileTasks = append(fileTasks[:i], fileTasks[i+1:]...)
Тут если поразбираться можно многое понять о том, как работают слайсы в Go.
Советую подумать, что тут происходит с точки зрения памяти, какие проблемы могли бы быть в теории.

2024-09-12 15:33 UTC, lazyfatcot commented on app/service.go
> +func (a *App) ListAllTasks() ([]models.Task, error) {
Если ты просто сделаешь

return a.Storage.LoadInfo()

То получишь ровно тот же самый результат

Проверка ошибки в этой функции не имеет никакого смысла.
Можно сэкономить пару строчек и сделать код чище.

2024-09-12 15:33 UTC, lazyfatcot commented on app/service.go
> +
У всех трех методов снизу один смысл, и в каждом из них у тебя лежит одинаковый код.

Можно добавить метод

```
func (a *App) listWithStatus(status string) ([]models.Task, error) {
    fileTasks, err := a.Storage.LoadInfo()
    ans = []

    if err != nil {
	return nil, err
    }

    for i, _ := range fileTasks {
        if fileTasks[i].Status == status { ans = append(ans, fileTasks[i]) }
    }
    return ans
}
```

И переиспользовать его в каждой конкретной реализации.
Или же вообще оставить только один этот метод, и вызывать его в хендлере

2024-09-12 15:33 UTC, lazyfatcot commented on app/service.go
> +
Тот же смысл. Все три Mark метода можно заменить одним.

func (a *App) Mark(id int, status string) ....

Чем меньше кода - тем лучше, тем легче его воспринимать.
Чем больше смысла в каждой строчке - тем лучше, та же логика.

Куча одинаковых циклов, где ты просто ищешь нужную запись по Id - это вода.

2024-09-15 17:06 UTC, pawwwline commented on storage/files/files.go
> +		defer func() {
закрыть файл, когда закончится основная функция, чтобы не потерялись данные и оптимизировать программу? ну по крайней мере я когда делала руководствовалась тем что почти всегда говорят мол нужно закрывать файлы, и соеденения с дб, а что... в этом нет смысла? или тут конкретно неправильно сделала?

2024-09-16 19:42 UTC, merged